name: staging
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: aptible/www-staging
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: quay.io
          buildargs: CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }},CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: aptible/aptible-deploy-action@v1
        with:
          username: ${{secrets.APTIBLE_ROBOT_USERNAME}}
          password: ${{secrets.APTIBLE_ROBOT_PASSWORD}}
          app: 'www-staging'
          environment: 'aptible-staging'
          docker_img: 'quay.io/aptible/www-staging'
